title: AI-ML 30DAYS COURSE
description: AI-ML 30DAYS COURSE
template:
  repo: ai-ml-30days-course-template
  name: ai-ml-30days-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
